server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: user-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/JuniorHub
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/juniorhubdb_user
    username: user
    password: password
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5